//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrOrm.SqLite.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrOrm.SqLite.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM test.user;
        ///
        ///ALTER SEQUENCE test.user_id_seq RESTART;
        ///.
        /// </summary>
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO test.user (name, email) VALUES (&apos;Bob&apos;, &apos;bob@gmail.com&apos;);
        ///INSERT INTO test.user (name, email) VALUES (&apos;Fred&apos;, &apos;fred@gmail.com&apos;);
        ///INSERT INTO test.user (name, email) VALUES (&apos;Jane&apos;, &apos;jane@gmail.com&apos;);
        ///INSERT INTO test.user (name, email) VALUES (&apos;Ed&apos;, &apos;ed@gmail.com&apos;);
        ///INSERT INTO test.user (name, email) VALUES (&apos;Jim&apos;, &apos;jim@gmail.com&apos;);
        ///INSERT INTO test.user (name, email) VALUES (&apos;Gary&apos;, &apos;gary@gmail.com&apos;);
        ///INSERT INTO test.user (name, email) VALUES (&apos;Bob&apos;, NULL);
        ///.
        /// </summary>
        internal static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SCHEMA test;
        ///
        ///CREATE TABLE test.user
        ///(
        ///  id serial NOT NULL,
        ///  name varchar NOT NULL,
        ///  email varchar
        ///) WITH (OIDS=FALSE);
        ///
        ///ALTER TABLE test.user
        ///  ADD CONSTRAINT pk_user
        ///  PRIMARY KEY (id);
        ///
        ///
        ///CREATE FUNCTION test.get_users()
        ///RETURNS TABLE(name varchar, email varchar)
        ///AS
        ///$$
        ///BEGIN
        ///  RETURN QUERY SELECT u.name, u.email FROM test.user u;
        ///END;
        ///$$
        ///LANGUAGE plpgsql;
        ///
        ///CREATE FUNCTION test.get_users(user_ids integer[])
        ///RETURNS TABLE(name varchar, email varchar)
        ///AS
        ///$$
        ///BEGIN
        ///  RETU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
